version: '3'

networks:
  node_net:
    driver: bridge

services:
  app:
    build: .
    image: node_back
    container_name: node_backend   # コンテナ名は別名を設定する
    tty: true
    volumes:
      - ./src:/app
    working_dir: "/app"
    ports:
      - 3000:3000 # ポートフォワーディングもかぶらないよう設定
    networks:
      - node_net